title:
  1: Many tiles
  2: Many tiles
testIn: |-
  -3 -3 0 2 1 4 3 6 5 8 7 9 10 11
  -2 -3 0 5 1 6 2 3 4 8 7 11 9 10
  -1 -3 0 11 1 8 2 10 3 7 4 5 6 9
  0 -3 0 3 1 10 2 6 4 8 5 7 9 11
  -3 -2 0 10 1 9 2 4 3 11 5 6 7 8
  -2 -2 0 3 1 4 2 7 5 11 6 8 9 10
  -1 -2 0 11 1 9 2 10 3 5 4 6 7 8
  0 -2 0 10 1 7 2 9 3 11 4 8 5 6
  1 -2 0 8 1 10 2 7 3 4 5 9 6 11
  -3 -1 0 5 1 2 3 4 6 8 7 11 9 10
  -2 -1 0 2 1 9 3 5 4 6 7 8 10 11
  -1 -1 0 5 1 2 3 7 4 9 6 10 8 11
  0 -1 0 6 1 10 2 3 4 5 7 11 8 9
  1 -1 0 10 1 7 2 3 4 9 5 11 6 8
  2 -1 0 9 1 2 3 4 5 7 6 8 10 11
  -3 0 0 11 1 2 3 6 4 7 5 10 8 9
  -2 0 0 8 1 3 2 9 4 5 6 7 10 11
  -1 0 0 1 2 9 3 5 4 10 6 7 8 11
  1 0 0 4 1 5 2 9 3 6 7 8 10 11
  2 0 0 8 1 9 2 5 3 10 4 6 7 11
  3 0 0 1 2 3 4 10 5 6 7 9 8 11
  -2 1 0 11 1 2 3 4 5 8 6 9 7 10
  -1 1 0 10 1 9 2 11 3 4 5 7 6 8
  0 1 0 9 1 10 2 8 3 4 5 11 6 7
  1 1 0 9 1 10 2 3 4 8 5 11 6 7
  2 1 0 8 1 10 2 7 3 4 5 11 6 9
  3 1 0 10 1 8 2 9 3 11 4 5 6 7
  -1 2 0 1 2 5 3 6 4 9 7 8 10 11
  0 2 0 8 1 4 2 6 3 10 5 11 7 9
  1 2 0 11 1 2 3 8 4 10 5 6 7 9
  2 2 0 2 1 10 3 11 4 9 5 7 6 8
  3 2 0 11 1 2 3 4 5 6 7 8 9 10
  0 3 0 11 1 3 2 4 5 9 6 8 7 10
  1 3 0 6 1 10 2 5 3 11 4 7 8 9
  2 3 0 1 2 3 4 10 5 11 6 9 7 8
  3 3 0 3 1 11 2 6 4 10 5 8 7 9
isTest: 'true'
isValidator: 'true'