title:
  1: Multi reuse
  2: Multi reuse
testIn: |-
  -3 -3 0 6 1 3 2 9 4 5 7 8 10 11
  -2 -3 0 7 1 8 2 5 3 10 4 11 6 9
  -1 -3 0 2 1 11 3 9 4 10 5 8 6 7
  0 -3 0 7 1 8 2 9 3 4 5 11 6 10
  -3 -2 0 3 1 5 2 8 4 9 6 7 10 11
  -2 -2 0 2 1 5 3 4 6 11 7 8 9 10
  -1 -2 0 9 1 10 2 4 3 11 5 6 7 8
  0 -2 0 5 1 9 2 10 3 4 6 11 7 8
  1 -2 0 1 2 10 3 6 4 7 5 9 8 11
  -3 -1 0 5 1 2 3 9 4 6 7 8 10 11
  -2 -1 0 3 1 7 2 9 4 8 5 6 10 11
  -1 -1 0 7 1 11 2 3 4 5 6 8 9 10
  0 -1 0 11 1 7 2 5 3 9 4 8 6 10
  1 -1 0 10 1 2 3 4 5 6 7 11 8 9
  2 -1 0 7 1 9 2 6 3 8 4 10 5 11
  -3 0 0 6 1 3 2 11 4 7 5 10 8 9
  -2 0 0 2 1 11 3 4 5 6 7 8 9 10
  -1 0 0 1 2 10 3 5 4 11 6 7 8 9
  1 0 0 11 1 5 2 8 3 6 4 10 7 9
  2 0 0 9 1 11 2 8 3 7 4 10 5 6
  3 0 0 10 1 9 2 3 4 5 6 8 7 11
  -2 1 0 6 1 3 2 7 4 8 5 11 9 10
  -1 1 0 11 1 4 2 9 3 10 5 6 7 8
  0 1 0 1 2 6 3 4 5 9 7 8 10 11
  1 1 0 5 1 8 2 6 3 4 7 9 10 11
  2 1 0 3 1 5 2 11 4 7 6 10 8 9
  3 1 0 6 1 7 2 10 3 4 5 8 9 11
  -1 2 0 7 1 8 2 3 4 10 5 9 6 11
  0 2 0 11 1 2 3 9 4 5 6 10 7 8
  1 2 0 4 1 3 2 7 5 8 6 10 9 11
  2 2 0 7 1 8 2 4 3 6 5 11 9 10
  3 2 0 10 1 5 2 8 3 11 4 9 6 7
  0 3 0 2 1 3 4 5 6 7 8 11 9 10
  1 3 0 2 1 6 3 5 4 11 7 10 8 9
  2 3 0 11 1 7 2 3 4 5 6 8 9 10
  3 3 0 6 1 7 2 9 3 5 4 11 8 10
isTest: 'false'
isValidator: 'true'