title:
  1: Sharp turns
  2: Sharp turns
testIn: |-
  -3 -3 0 6 1 3 2 10 4 5 7 9 8 11
  -2 -3 0 1 2 10 3 4 5 8 6 7 9 11
  -1 -3 0 10 1 3 2 7 4 8 5 11 6 9
  0 -3 0 7 1 5 2 11 3 4 6 10 8 9
  -3 -2 0 11 1 10 2 3 4 5 6 7 8 9
  -2 -2 0 8 1 5 2 4 3 7 6 11 9 10
  -1 -2 0 2 1 9 3 6 4 5 7 11 8 10
  0 -2 0 10 1 7 2 4 3 9 5 11 6 8
  1 -2 0 1 2 10 3 6 4 11 5 8 7 9
  -3 -1 0 1 2 5 3 10 4 8 6 7 9 11
  -2 -1 0 6 1 9 2 10 3 5 4 8 7 11
  -1 -1 0 4 1 2 3 7 5 6 8 9 10 11
  0 -1 0 11 1 3 2 8 4 7 5 9 6 10
  1 -1 0 7 1 4 2 3 5 11 6 10 8 9
  2 -1 0 3 1 2 4 10 5 6 7 8 9 11
  -3 0 0 6 1 7 2 4 3 11 5 9 8 10
  -2 0 0 7 1 3 2 4 5 10 6 11 8 9
  -1 0 0 2 1 7 3 11 4 5 6 9 8 10
  1 0 0 3 1 10 2 8 4 5 6 7 9 11
  2 0 0 1 2 6 3 10 4 11 5 8 7 9
  3 0 0 8 1 6 2 11 3 9 4 7 5 10
  -2 1 0 10 1 11 2 7 3 5 4 6 8 9
  -1 1 0 1 2 3 4 5 6 7 8 9 10 11
  0 1 0 10 1 3 2 8 4 6 5 7 9 11
  1 1 0 2 1 11 3 8 4 6 5 7 9 10
  2 1 0 6 1 8 2 5 3 10 4 9 7 11
  3 1 0 11 1 8 2 10 3 6 4 9 5 7
  -1 2 0 4 1 10 2 3 5 7 6 8 9 11
  0 2 0 2 1 11 3 5 4 6 7 9 8 10
  1 2 0 1 2 3 4 5 6 7 8 9 10 11
  2 2 0 10 1 4 2 7 3 5 6 8 9 11
  3 2 0 3 1 6 2 4 5 9 7 10 8 11
  0 3 0 9 1 6 2 3 4 11 5 10 7 8
  1 3 0 3 1 4 2 11 5 7 6 8 9 10
  2 3 0 4 1 2 3 6 5 11 7 9 8 10
  3 3 0 5 1 9 2 7 3 4 6 8 10 11
isTest: 'true'
isValidator: 'false'