title:
  1: Fail-In-Two
  2: Fail-In-Two
testIn: |-
  -3 -3 0 8 1 11 2 5 3 6 4 10 7 9
  -2 -3 0 1 2 5 3 9 4 6 7 8 10 11
  -1 -3 0 1 2 9 3 11 4 7 5 10 6 8
  0 -3 0 8 1 11 2 4 3 9 5 6 7 10
  -3 -2 0 2 1 11 3 9 4 10 5 6 7 8
  -2 -2 0 9 1 2 3 11 4 5 6 10 7 8
  -1 -2 0 5 1 11 2 4 3 6 7 8 9 10
  0 -2 0 4 1 2 3 11 5 6 7 8 9 10
  1 -2 0 10 1 4 2 6 3 11 5 9 7 8
  -3 -1 0 2 1 7 3 11 4 5 6 8 9 10
  -2 -1 0 1 2 9 3 4 5 7 6 8 10 11
  -1 -1 0 11 1 9 2 10 3 5 4 6 7 8
  0 -1 0 2 1 3 4 6 5 7 8 10 9 11
  1 -1 0 6 1 8 2 3 4 5 7 11 9 10
  2 -1 0 1 2 4 3 8 5 6 7 9 10 11
  -3 0 0 11 1 3 2 4 5 9 6 8 7 10
  -2 0 0 8 1 4 2 3 5 10 6 11 7 9
  -1 0 0 9 1 2 3 8 4 7 5 6 10 11
  1 0 0 10 1 2 3 7 4 6 5 8 9 11
  2 0 0 4 1 9 2 3 5 8 6 7 10 11
  3 0 0 2 1 10 3 4 5 11 6 9 7 8
  -2 1 0 8 1 4 2 11 3 9 5 6 7 10
  -1 1 0 7 1 9 2 3 4 10 5 8 6 11
  0 1 0 3 1 4 2 8 5 11 6 7 9 10
  1 1 0 1 2 7 3 11 4 8 5 10 6 9
  2 1 0 11 1 8 2 4 3 7 5 6 9 10
  3 1 0 4 1 11 2 7 3 6 5 10 8 9
  -1 2 0 5 1 7 2 8 3 4 6 9 10 11
  0 2 0 4 1 8 2 10 3 11 5 6 7 9
  1 2 0 5 1 6 2 7 3 8 4 9 10 11
  2 2 0 7 1 3 2 10 4 11 5 8 6 9
  3 2 0 11 1 9 2 10 3 7 4 5 6 8
  0 3 0 11 1 6 2 5 3 7 4 9 8 10
  1 3 0 11 1 10 2 3 4 6 5 8 7 9
  2 3 0 11 1 8 2 5 3 6 4 7 9 10
  3 3 0 6 1 8 2 11 3 7 4 5 9 10
isTest: 'true'
isValidator: 'false'