title:
  1: Combo breaker
  2: Combo breaker
testIn: |-
  -3 -3 0 10 1 11 2 7 3 5 4 9 6 8
  -2 -3 0 10 1 4 2 3 5 6 7 8 9 11
  -1 -3 0 11 1 2 3 5 4 8 6 7 9 10
  0 -3 0 1 2 3 4 8 5 7 6 10 9 11
  -3 -2 0 7 1 2 3 8 4 5 6 11 9 10
  -2 -2 0 9 1 3 2 4 5 6 7 11 8 10
  -1 -2 0 6 1 10 2 9 3 11 4 7 5 8
  0 -2 0 8 1 6 2 5 3 11 4 10 7 9
  1 -2 0 11 1 3 2 10 4 9 5 6 7 8
  -3 -1 0 10 1 8 2 3 4 5 6 7 9 11
  -2 -1 0 2 1 6 3 10 4 11 5 9 7 8
  -1 -1 0 5 1 3 2 10 4 11 6 8 7 9
  0 -1 0 10 1 7 2 5 3 4 6 11 8 9
  1 -1 0 8 1 9 2 3 4 6 5 7 10 11
  2 -1 0 1 2 3 4 5 6 7 8 9 10 11
  -3 0 0 1 2 3 4 9 5 8 6 7 10 11
  -2 0 0 1 2 7 3 6 4 5 8 9 10 11
  -1 0 0 3 1 7 2 11 4 9 5 6 8 10
  1 0 0 6 1 2 3 4 5 11 7 8 9 10
  2 0 0 5 1 6 2 3 4 8 7 10 9 11
  3 0 0 1 2 7 3 6 4 8 5 11 9 10
  -2 1 0 11 1 3 2 9 4 6 5 7 8 10
  -1 1 0 11 1 6 2 4 3 10 5 9 7 8
  0 1 0 5 1 7 2 3 4 6 8 9 10 11
  1 1 0 2 1 7 3 5 4 11 6 8 9 10
  2 1 0 11 1 10 2 3 4 5 6 9 7 8
  3 1 0 5 1 11 2 3 4 9 6 10 7 8
  -1 2 0 5 1 8 2 11 3 4 6 7 9 10
  0 2 0 2 1 10 3 7 4 9 5 8 6 11
  1 2 0 1 2 7 3 11 4 10 5 8 6 9
  2 2 0 8 1 2 3 4 5 6 7 9 10 11
  3 2 0 8 1 11 2 4 3 6 5 10 7 9
  0 3 0 6 1 9 2 5 3 11 4 7 8 10
  1 3 0 2 1 5 3 11 4 7 6 8 9 10
  2 3 0 8 1 10 2 9 3 6 4 7 5 11
  3 3 0 8 1 9 2 5 3 6 4 7 10 11
isTest: 'false'
isValidator: 'true'