title:
  1: Many tiles
  2: Many tiles
testIn: |-
  -3 -3 0 5 1 2 3 9 4 7 6 8 10 11
  -2 -3 0 2 1 5 3 10 4 9 6 11 7 8
  -1 -3 0 1 2 9 3 7 4 8 5 10 6 11
  0 -3 0 1 2 7 3 5 4 9 6 8 10 11
  -3 -2 0 7 1 3 2 6 4 5 8 9 10 11
  -2 -2 0 2 1 7 3 11 4 10 5 6 8 9
  -1 -2 0 11 1 5 2 3 4 6 7 8 9 10
  0 -2 0 11 1 5 2 3 4 8 6 9 7 10
  1 -2 0 8 1 9 2 4 3 10 5 6 7 11
  -3 -1 0 3 1 6 2 11 4 8 5 7 9 10
  -2 -1 0 11 1 4 2 8 3 7 5 9 6 10
  -1 -1 0 11 1 5 2 9 3 6 4 8 7 10
  0 -1 0 3 1 11 2 4 5 6 7 8 9 10
  1 -1 0 3 1 2 4 10 5 7 6 11 8 9
  2 -1 0 8 1 10 2 5 3 11 4 9 6 7
  -3 0 0 3 1 10 2 11 4 7 5 9 6 8
  -2 0 0 6 1 9 2 4 3 10 5 7 8 11
  -1 0 0 11 1 2 3 5 4 8 6 7 9 10
  1 0 0 1 2 10 3 11 4 6 5 9 7 8
  2 0 0 1 2 4 3 11 5 6 7 8 9 10
  3 0 0 4 1 2 3 7 5 6 8 11 9 10
  -2 1 0 11 1 3 2 6 4 8 5 7 9 10
  -1 1 0 11 1 5 2 9 3 10 4 6 7 8
  0 1 0 1 2 11 3 5 4 8 6 7 9 10
  1 1 0 1 2 6 3 10 4 11 5 8 7 9
  2 1 0 1 2 3 4 9 5 6 7 8 10 11
  3 1 0 9 1 4 2 5 3 10 6 7 8 11
  -1 2 0 8 1 9 2 3 4 6 5 11 7 10
  0 2 0 4 1 9 2 5 3 10 6 11 7 8
  1 2 0 11 1 7 2 3 4 8 5 6 9 10
  2 2 0 2 1 5 3 4 6 8 7 9 10 11
  3 2 0 3 1 4 2 10 5 6 7 11 8 9
  0 3 0 8 1 10 2 11 3 9 4 5 6 7
  1 3 0 1 2 8 3 5 4 11 6 7 9 10
  2 3 0 4 1 10 2 8 3 9 5 6 7 11
  3 3 0 1 2 3 4 7 5 11 6 10 8 9
isTest: 'false'
isValidator: 'true'