title:
  1: Medium Turns
  2: Medium Turns
testIn: |-
  -3 -3 0 6 1 9 2 3 4 7 5 10 8 11
  -2 -3 0 5 1 2 3 7 4 6 8 9 10 11
  -1 -3 0 9 1 4 2 6 3 5 7 11 8 10
  0 -3 0 1 2 3 4 7 5 6 8 9 10 11
  -3 -2 0 2 1 3 4 5 6 11 7 10 8 9
  -2 -2 0 1 2 3 4 8 5 9 6 10 7 11
  -1 -2 0 11 1 3 2 7 4 8 5 6 9 10
  0 -2 0 4 1 5 2 6 3 7 8 9 10 11
  1 -2 0 6 1 9 2 8 3 7 4 5 10 11
  -3 -1 0 10 1 6 2 3 4 7 5 8 9 11
  -2 -1 0 1 2 11 3 9 4 8 5 7 6 10
  -1 -1 0 7 1 3 2 6 4 11 5 10 8 9
  0 -1 0 7 1 2 3 4 5 6 8 11 9 10
  1 -1 0 7 1 2 3 8 4 11 5 6 9 10
  2 -1 0 11 1 3 2 8 4 9 5 6 7 10
  -3 0 0 11 1 2 3 10 4 5 6 9 7 8
  -2 0 0 8 1 9 2 10 3 11 4 5 6 7
  -1 0 0 7 1 10 2 4 3 8 5 11 6 9
  1 0 0 3 1 4 2 11 5 6 7 9 8 10
  2 0 0 8 1 9 2 10 3 11 4 5 6 7
  3 0 0 5 1 4 2 8 3 7 6 11 9 10
  -2 1 0 1 2 11 3 9 4 6 5 7 8 10
  -1 1 0 3 1 6 2 5 4 9 7 11 8 10
  0 1 0 11 1 2 3 4 5 8 6 7 9 10
  1 1 0 10 1 2 3 6 4 7 5 8 9 11
  2 1 0 1 2 11 3 4 5 10 6 7 8 9
  3 1 0 11 1 6 2 7 3 5 4 10 8 9
  -1 2 0 7 1 10 2 11 3 4 5 8 6 9
  0 2 0 4 1 5 2 6 3 7 8 9 10 11
  1 2 0 3 1 2 4 11 5 6 7 8 9 10
  2 2 0 1 2 3 4 8 5 9 6 10 7 11
  3 2 0 9 1 6 2 8 3 5 4 7 10 11
  0 3 0 2 1 9 3 11 4 5 6 7 8 10
  1 3 0 3 1 4 2 5 6 7 8 9 10 11
  2 3 0 2 1 4 3 9 5 10 6 7 8 11
  3 3 0 4 1 7 2 9 3 8 5 10 6 11
isTest: 'true'
isValidator: 'false'