title:
  1: Big Score
  2: Big Score
testIn: |-
  -3 -3 0 10 1 7 2 3 4 6 5 9 8 11
  -2 -3 0 2 1 7 3 4 5 6 8 10 9 11
  -1 -3 0 1 2 6 3 7 4 5 8 9 10 11
  0 -3 0 2 1 9 3 11 4 6 5 10 7 8
  -3 -2 0 7 1 8 2 11 3 5 4 6 9 10
  -2 -2 0 10 1 6 2 8 3 4 5 7 9 11
  -1 -2 0 8 1 2 3 5 4 11 6 7 9 10
  0 -2 0 6 1 5 2 10 3 11 4 7 8 9
  1 -2 0 8 1 7 2 3 4 5 6 11 9 10
  -3 -1 0 2 1 10 3 7 4 5 6 9 8 11
  -2 -1 0 3 1 2 4 11 5 8 6 9 7 10
  -1 -1 0 4 1 10 2 11 3 7 5 6 8 9
  0 -1 0 9 1 2 3 4 5 10 6 7 8 11
  1 -1 0 3 1 5 2 11 4 6 7 8 9 10
  2 -1 0 7 1 9 2 4 3 10 5 8 6 11
  -3 0 0 3 1 2 4 5 6 10 7 8 9 11
  -2 0 0 11 1 2 3 4 5 7 6 10 8 9
  -1 0 0 1 2 10 3 11 4 5 6 8 7 9
  1 0 0 3 1 2 4 7 5 6 8 9 10 11
  2 0 0 6 1 7 2 4 3 5 8 11 9 10
  3 0 0 7 1 8 2 5 3 6 4 11 9 10
  -2 1 0 9 1 11 2 6 3 7 4 5 8 10
  -1 1 0 9 1 2 3 4 5 7 6 11 8 10
  0 1 0 11 1 2 3 8 4 5 6 7 9 10
  1 1 0 10 1 3 2 4 5 7 6 11 8 9
  2 1 0 3 1 7 2 6 4 5 8 9 10 11
  3 1 0 1 2 3 4 9 5 10 6 8 7 11
  -1 2 0 10 1 11 2 7 3 5 4 6 8 9
  0 2 0 3 1 7 2 5 4 11 6 8 9 10
  1 2 0 5 1 9 2 10 3 7 4 8 6 11
  2 2 0 8 1 2 3 10 4 6 5 7 9 11
  3 2 0 6 1 9 2 10 3 4 5 11 7 8
  0 3 0 3 1 2 4 9 5 11 6 7 8 10
  1 3 0 10 1 5 2 3 4 8 6 7 9 11
  2 3 0 11 1 7 2 3 4 10 5 6 8 9
  3 3 0 11 1 6 2 4 3 5 7 9 8 10
isTest: 'false'
isValidator: 'true'