title:
  1: Sharp turns
  2: Sharp turns
testIn: |-
  -3 -3 0 2 1 7 3 6 4 5 8 10 9 11
  -2 -3 0 8 1 3 2 4 5 7 6 10 9 11
  -1 -3 0 2 1 11 3 7 4 5 6 10 8 9
  0 -3 0 9 1 6 2 5 3 8 4 11 7 10
  -3 -2 0 2 1 7 3 11 4 9 5 6 8 10
  -2 -2 0 2 1 10 3 5 4 6 7 11 8 9
  -1 -2 0 1 2 3 4 5 6 7 8 9 10 11
  0 -2 0 10 1 3 2 4 5 7 6 8 9 11
  1 -2 0 2 1 11 3 5 4 8 6 7 9 10
  -3 -1 0 1 2 9 3 6 4 7 5 10 8 11
  -2 -1 0 7 1 9 2 11 3 6 4 10 5 8
  -1 -1 0 1 2 11 3 4 5 7 6 8 9 10
  0 -1 0 9 1 6 2 11 3 5 4 7 8 10
  1 -1 0 1 2 3 4 5 6 7 8 9 10 11
  2 -1 0 10 1 8 2 5 3 7 4 6 9 11
  -3 0 0 8 1 2 3 6 4 9 5 11 7 10
  -2 0 0 2 1 8 3 5 4 7 6 9 10 11
  -1 0 0 5 1 3 2 6 4 7 8 11 9 10
  1 0 0 4 1 2 3 11 5 7 6 8 9 10
  2 0 0 2 1 5 3 4 6 11 7 9 8 10
  3 0 0 10 1 3 2 11 4 5 6 8 7 9
  -2 1 0 11 1 3 2 6 4 5 7 8 9 10
  -1 1 0 7 1 6 2 4 3 8 5 10 9 11
  0 1 0 7 1 9 2 4 3 5 6 8 10 11
  1 1 0 6 1 4 2 3 5 8 7 11 9 10
  2 1 0 8 1 3 2 7 4 9 5 10 6 11
  3 1 0 11 1 3 2 5 4 6 7 8 9 10
  -1 2 0 4 1 5 2 7 3 10 6 8 9 11
  0 2 0 7 1 2 3 5 4 9 6 11 8 10
  1 2 0 4 1 7 2 3 5 9 6 10 8 11
  2 2 0 8 1 10 2 7 3 11 4 9 5 6
  3 2 0 9 1 8 2 5 3 10 4 7 6 11
  0 3 0 7 1 11 2 4 3 5 6 8 9 10
  1 3 0 9 1 4 2 10 3 8 5 11 6 7
  2 3 0 10 1 7 2 6 3 4 5 9 8 11
  3 3 0 8 1 2 3 10 4 9 5 11 6 7
isTest: 'false'
isValidator: 'true'