title:
  1: Combo breaker
  2: Combo breaker
testIn: |-
  -3 -3 0 1 2 8 3 4 5 9 6 11 7 10
  -2 -3 0 1 2 3 4 5 6 7 8 9 10 11
  -1 -3 0 10 1 2 3 11 4 9 5 6 7 8
  0 -3 0 1 2 4 3 7 5 9 6 8 10 11
  -3 -2 0 2 1 8 3 7 4 9 5 6 10 11
  -2 -2 0 7 1 8 2 4 3 6 5 9 10 11
  -1 -2 0 4 1 5 2 3 6 8 7 9 10 11
  0 -2 0 7 1 5 2 10 3 9 4 6 8 11
  1 -2 0 11 1 2 3 4 5 9 6 7 8 10
  -3 -1 0 2 1 5 3 8 4 6 7 10 9 11
  -2 -1 0 3 1 2 4 7 5 6 8 9 10 11
  -1 -1 0 11 1 7 2 8 3 4 5 6 9 10
  0 -1 0 3 1 6 2 7 4 5 8 11 9 10
  1 -1 0 3 1 7 2 10 4 11 5 8 6 9
  2 -1 0 9 1 3 2 4 5 6 7 8 10 11
  -3 0 0 4 1 5 2 3 6 9 7 10 8 11
  -2 0 0 11 1 5 2 3 4 6 7 8 9 10
  -1 0 0 6 1 11 2 9 3 4 5 7 8 10
  1 0 0 10 1 8 2 9 3 11 4 6 5 7
  2 0 0 10 1 4 2 6 3 5 7 8 9 11
  3 0 0 2 1 3 4 9 5 7 6 11 8 10
  -2 1 0 3 1 5 2 8 4 11 6 9 7 10
  -1 1 0 1 2 10 3 9 4 7 5 8 6 11
  0 1 0 6 1 8 2 3 4 5 7 9 10 11
  1 1 0 6 1 10 2 11 3 5 4 9 7 8
  2 1 0 7 1 11 2 9 3 10 4 8 5 6
  3 1 0 11 1 6 2 7 3 4 5 10 8 9
  -1 2 0 8 1 11 2 10 3 4 5 7 6 9
  0 2 0 3 1 11 2 7 4 9 5 8 6 10
  1 2 0 7 1 2 3 10 4 8 5 6 9 11
  2 2 0 1 2 3 4 5 6 11 7 10 8 9
  3 2 0 5 1 3 2 4 6 7 8 9 10 11
  0 3 0 4 1 7 2 10 3 5 6 9 8 11
  1 3 0 5 1 8 2 11 3 4 6 7 9 10
  2 3 0 10 1 2 3 5 4 11 6 8 7 9
  3 3 0 1 2 3 4 9 5 8 6 7 10 11
isTest: 'true'
isValidator: 'false'