title:
  1: Meh
  2: Meh
testIn: |-
  -3 -3 0 7 1 3 2 8 4 9 5 11 6 10
  -2 -3 0 5 1 2 3 8 4 7 6 9 10 11
  -1 -3 0 1 2 4 3 9 5 6 7 8 10 11
  0 -3 0 11 1 7 2 5 3 4 6 10 8 9
  -3 -2 0 2 1 7 3 6 4 10 5 8 9 11
  -2 -2 0 1 2 7 3 10 4 5 6 9 8 11
  -1 -2 0 9 1 7 2 8 3 10 4 11 5 6
  0 -2 0 7 1 5 2 3 4 6 8 10 9 11
  1 -2 0 6 1 7 2 5 3 10 4 11 8 9
  -3 -1 0 1 2 11 3 7 4 10 5 6 8 9
  -2 -1 0 10 1 4 2 9 3 5 6 11 7 8
  -1 -1 0 6 1 10 2 11 3 7 4 8 5 9
  0 -1 0 9 1 7 2 8 3 6 4 5 10 11
  1 -1 0 3 1 8 2 7 4 9 5 6 10 11
  2 -1 0 7 1 5 2 3 4 6 8 9 10 11
  -3 0 0 5 1 4 2 6 3 8 7 10 9 11
  -2 0 0 2 1 8 3 7 4 9 5 6 10 11
  -1 0 0 3 1 7 2 9 4 6 5 8 10 11
  1 0 0 6 1 10 2 11 3 7 4 8 5 9
  2 0 0 6 1 2 3 10 4 5 7 11 8 9
  3 0 0 7 1 4 2 11 3 9 5 6 8 10
  -2 1 0 1 2 4 3 8 5 6 7 11 9 10
  -1 1 0 9 1 5 2 10 3 4 6 8 7 11
  0 1 0 11 1 3 2 5 4 6 7 10 8 9
  1 1 0 1 2 11 3 4 5 6 7 10 8 9
  2 1 0 4 1 7 2 8 3 6 5 9 10 11
  3 1 0 11 1 10 2 9 3 6 4 7 5 8
  -1 2 0 2 1 7 3 5 4 6 8 9 10 11
  0 2 0 3 1 6 2 7 4 8 5 10 9 11
  1 2 0 2 1 6 3 5 4 8 7 10 9 11
  2 2 0 11 1 2 3 4 5 6 7 10 8 9
  3 2 0 8 1 2 3 11 4 5 6 7 9 10
  0 3 0 10 1 11 2 5 3 8 4 6 7 9
  1 3 0 1 2 4 3 5 6 7 8 10 9 11
  2 3 0 4 1 6 2 3 5 10 7 8 9 11
  3 3 0 2 1 3 4 5 6 11 7 10 8 9
isTest: 'false'
isValidator: 'true'