title:
  1: Think
  2: Think
testIn: |-
  -3 -3 0 3 1 4 2 10 5 8 6 7 9 11
  -2 -3 0 3 1 11 2 5 4 10 6 8 7 9
  -1 -3 0 2 1 11 3 6 4 5 7 8 9 10
  0 -3 0 1 2 8 3 10 4 11 5 9 6 7
  -3 -2 0 10 1 9 2 5 3 11 4 8 6 7
  -2 -2 0 3 1 5 2 6 4 8 7 11 9 10
  -1 -2 0 8 1 4 2 7 3 9 5 10 6 11
  0 -2 0 6 1 7 2 11 3 4 5 8 9 10
  1 -2 0 11 1 7 2 10 3 6 4 5 8 9
  -3 -1 0 8 1 5 2 9 3 4 6 7 10 11
  -2 -1 0 5 1 9 2 7 3 8 4 11 6 10
  -1 -1 0 6 1 11 2 8 3 5 4 10 7 9
  0 -1 0 11 1 7 2 4 3 10 5 8 6 9
  1 -1 0 4 1 5 2 11 3 8 6 9 7 10
  2 -1 0 4 1 2 3 11 5 10 6 7 8 9
  -3 0 0 11 1 2 3 5 4 7 6 10 8 9
  -2 0 0 7 1 6 2 11 3 9 4 5 8 10
  -1 0 0 2 1 4 3 8 5 11 6 7 9 10
  1 0 0 2 1 3 4 5 6 11 7 9 8 10
  2 0 0 4 1 5 2 8 3 11 6 7 9 10
  3 0 0 11 1 4 2 3 5 8 6 10 7 9
  -2 1 0 6 1 9 2 8 3 4 5 7 10 11
  -1 1 0 4 1 5 2 7 3 6 8 9 10 11
  0 1 0 9 1 4 2 11 3 5 6 7 8 10
  1 1 0 1 2 10 3 8 4 5 6 11 7 9
  2 1 0 5 1 7 2 8 3 9 4 11 6 10
  3 1 0 11 1 7 2 8 3 4 5 6 9 10
  -1 2 0 1 2 5 3 8 4 11 6 9 7 10
  0 2 0 3 1 10 2 7 4 9 5 11 6 8
  1 2 0 1 2 3 4 11 5 9 6 7 8 10
  2 2 0 1 2 7 3 9 4 5 6 11 8 10
  3 2 0 3 1 9 2 11 4 10 5 6 7 8
  0 3 0 5 1 4 2 11 3 8 6 7 9 10
  1 3 0 1 2 9 3 8 4 10 5 7 6 11
  2 3 0 2 1 11 3 10 4 7 5 6 8 9
  3 3 0 1 2 4 3 6 5 9 7 8 10 11
isTest: 'true'
isValidator: 'false'