title:
  1: Sharp Turns
  2: Sharp Turns
testIn: |-
  -3 -3 0 8 1 11 2 7 3 6 4 5 9 10
  -2 -3 0 11 1 9 2 3 4 8 5 10 6 7
  -1 -3 0 1 2 7 3 9 4 10 5 11 6 8
  0 -3 0 9 1 5 2 6 3 11 4 10 7 8
  -3 -2 0 1 2 5 3 6 4 7 8 10 9 11
  -2 -2 0 1 2 5 3 4 6 9 7 8 10 11
  -1 -2 0 3 1 4 2 5 6 9 7 10 8 11
  0 -2 0 1 2 3 4 7 5 6 8 9 10 11
  1 -2 0 1 2 6 3 7 4 8 5 9 10 11
  -3 -1 0 7 1 9 2 11 3 4 5 8 6 10
  -2 -1 0 7 1 9 2 8 3 10 4 5 6 11
  -1 -1 0 2 1 11 3 10 4 9 5 8 6 7
  0 -1 0 11 1 7 2 6 3 5 4 9 8 10
  1 -1 0 3 1 4 2 5 6 9 7 10 8 11
  2 -1 0 8 1 4 2 9 3 6 5 7 10 11
  -3 0 0 8 1 3 2 10 4 7 5 9 6 11
  -2 0 0 11 1 7 2 3 4 6 5 8 9 10
  -1 0 0 1 2 8 3 6 4 7 5 11 9 10
  1 0 0 3 1 6 2 5 4 10 7 8 9 11
  2 0 0 6 1 11 2 10 3 7 4 5 8 9
  3 0 0 6 1 4 2 3 5 10 7 11 8 9
  -2 1 0 8 1 3 2 11 4 5 6 9 7 10
  -1 1 0 9 1 10 2 11 3 6 4 7 5 8
  0 1 0 1 2 3 4 10 5 11 6 9 7 8
  1 1 0 8 1 10 2 4 3 9 5 7 6 11
  2 1 0 3 1 6 2 7 4 8 5 9 10 11
  3 1 0 7 1 4 2 6 3 10 5 11 8 9
  -1 2 0 5 1 2 3 4 6 7 8 11 9 10
  0 2 0 10 1 6 2 7 3 11 4 5 8 9
  1 2 0 9 1 10 2 11 3 6 4 7 5 8
  2 2 0 2 1 3 4 5 6 7 8 9 10 11
  3 2 0 5 1 4 2 9 3 10 6 8 7 11
  0 3 0 6 1 5 2 4 3 8 7 10 9 11
  1 3 0 3 1 11 2 4 5 8 6 7 9 10
  2 3 0 11 1 5 2 10 3 6 4 7 8 9
  3 3 0 9 1 8 2 11 3 5 4 10 6 7
isTest: 'false'
isValidator: 'true'