title:
  1: Gentle Curves
  2: Gentle Curves
testIn: |-
  -3 -3 0 10 1 5 2 3 4 6 7 11 8 9
  -2 -3 0 1 2 3 4 9 5 8 6 7 10 11
  -1 -3 0 11 1 5 2 8 3 9 4 10 6 7
  0 -3 0 4 1 3 2 11 5 6 7 10 8 9
  -3 -2 0 9 1 7 2 10 3 8 4 5 6 11
  -2 -2 0 5 1 8 2 7 3 10 4 9 6 11
  -1 -2 0 7 1 5 2 11 3 10 4 9 6 8
  0 -2 0 3 1 4 2 11 5 10 6 9 7 8
  1 -2 0 4 1 6 2 10 3 9 5 7 8 11
  -3 -1 0 2 1 9 3 4 5 6 7 8 10 11
  -2 -1 0 3 1 10 2 8 4 5 6 7 9 11
  -1 -1 0 5 1 10 2 9 3 11 4 8 6 7
  0 -1 0 9 1 3 2 11 4 6 5 8 7 10
  1 -1 0 4 1 3 2 10 5 7 6 9 8 11
  2 -1 0 1 2 4 3 7 5 9 6 8 10 11
  -3 0 0 2 1 6 3 7 4 5 8 9 10 11
  -2 0 0 8 1 5 2 9 3 6 4 7 10 11
  -1 0 0 5 1 4 2 6 3 11 7 8 9 10
  1 0 0 3 1 7 2 11 4 9 5 6 8 10
  2 0 0 5 1 8 2 7 3 10 4 9 6 11
  3 0 0 4 1 3 2 5 6 9 7 8 10 11
  -2 1 0 8 1 3 2 6 4 9 5 10 7 11
  -1 1 0 4 1 11 2 6 3 10 5 8 7 9
  0 1 0 1 2 11 3 7 4 5 6 9 8 10
  1 1 0 8 1 7 2 4 3 10 5 6 9 11
  2 1 0 11 1 8 2 5 3 4 6 7 9 10
  3 1 0 11 1 7 2 10 3 6 4 5 8 9
  -1 2 0 1 2 9 3 5 4 8 6 7 10 11
  0 2 0 1 2 8 3 6 4 7 5 11 9 10
  1 2 0 3 1 11 2 6 4 10 5 7 8 9
  2 2 0 8 1 11 2 10 3 7 4 5 6 9
  3 2 0 8 1 3 2 6 4 7 5 11 9 10
  0 3 0 1 2 7 3 11 4 9 5 8 6 10
  1 3 0 10 1 5 2 6 3 4 7 11 8 9
  2 3 0 10 1 5 2 8 3 9 4 6 7 11
  3 3 0 2 1 8 3 9 4 11 5 7 6 10
isTest: 'true'
isValidator: 'false'