title:
  1: Multi reuse
  2: Multi reuse
testIn: |-
  -3 -3 0 4 1 11 2 3 5 7 6 10 8 9
  -2 -3 0 11 1 6 2 9 3 4 5 10 7 8
  -1 -3 0 8 1 6 2 11 3 4 5 9 7 10
  0 -3 0 8 1 11 2 3 4 7 5 10 6 9
  -3 -2 0 6 1 9 2 8 3 4 5 10 7 11
  -2 -2 0 2 1 8 3 4 5 11 6 10 7 9
  -1 -2 0 9 1 4 2 10 3 8 5 11 6 7
  0 -2 0 9 1 7 2 4 3 5 6 10 8 11
  1 -2 0 3 1 4 2 10 5 6 7 11 8 9
  -3 -1 0 3 1 5 2 9 4 10 6 11 7 8
  -2 -1 0 4 1 9 2 10 3 8 5 6 7 11
  -1 -1 0 8 1 6 2 10 3 11 4 9 5 7
  0 -1 0 8 1 5 2 10 3 11 4 6 7 9
  1 -1 0 3 1 4 2 10 5 11 6 7 8 9
  2 -1 0 1 2 3 4 5 6 7 8 11 9 10
  -3 0 0 9 1 2 3 10 4 5 6 11 7 8
  -2 0 0 3 1 10 2 9 4 6 5 11 7 8
  -1 0 0 4 1 10 2 5 3 6 7 8 9 11
  1 0 0 2 1 5 3 9 4 7 6 11 8 10
  2 0 0 11 1 8 2 3 4 9 5 6 7 10
  3 0 0 6 1 5 2 10 3 9 4 7 8 11
  -2 1 0 4 1 10 2 11 3 7 5 9 6 8
  -1 1 0 9 1 5 2 3 4 7 6 11 8 10
  0 1 0 5 1 11 2 4 3 9 6 10 7 8
  1 1 0 10 1 3 2 7 4 9 5 6 8 11
  2 1 0 8 1 10 2 5 3 6 4 9 7 11
  3 1 0 3 1 5 2 4 6 10 7 8 9 11
  -1 2 0 3 1 9 2 11 4 5 6 10 7 8
  0 2 0 11 1 2 3 9 4 6 5 8 7 10
  1 2 0 8 1 2 3 5 4 7 6 9 10 11
  2 2 0 6 1 11 2 7 3 4 5 8 9 10
  3 2 0 5 1 9 2 4 3 10 6 8 7 11
  0 3 0 11 1 3 2 7 4 6 5 10 8 9
  1 3 0 4 1 11 2 5 3 9 6 7 8 10
  2 3 0 5 1 11 2 3 4 6 7 9 8 10
  3 3 0 10 1 4 2 3 5 6 7 11 8 9
isTest: 'true'
isValidator: 'false'