title:
  1: More simple reuses
  2: More simple reuses
testIn: |-
  -3 -3 0 9 1 2 3 8 4 5 6 7 10 11
  -2 -3 0 1 2 11 3 8 4 5 6 10 7 9
  -1 -3 0 9 1 2 3 6 4 5 7 10 8 11
  0 -3 0 1 2 10 3 8 4 11 5 9 6 7
  -3 -2 0 8 1 3 2 4 5 10 6 11 7 9
  -2 -2 0 4 1 11 2 3 5 9 6 7 8 10
  -1 -2 0 10 1 6 2 3 4 5 7 8 9 11
  0 -2 0 4 1 3 2 5 6 7 8 9 10 11
  1 -2 0 6 1 10 2 11 3 9 4 5 7 8
  -3 -1 0 1 2 8 3 5 4 6 7 9 10 11
  -2 -1 0 11 1 8 2 5 3 4 6 7 9 10
  -1 -1 0 10 1 7 2 11 3 9 4 8 5 6
  0 -1 0 2 1 11 3 4 5 8 6 9 7 10
  1 -1 0 2 1 5 3 6 4 8 7 9 10 11
  2 -1 0 7 1 11 2 10 3 4 5 6 8 9
  -3 0 0 4 1 9 2 6 3 11 5 7 8 10
  -2 0 0 10 1 11 2 8 3 4 5 7 6 9
  -1 0 0 11 1 10 2 7 3 9 4 6 5 8
  1 0 0 2 1 6 3 7 4 11 5 10 8 9
  2 0 0 11 1 3 2 10 4 6 5 7 8 9
  3 0 0 11 1 2 3 6 4 7 5 10 8 9
  -2 1 0 1 2 6 3 7 4 11 5 8 9 10
  -1 1 0 4 1 2 3 5 6 7 8 10 9 11
  0 1 0 4 1 2 3 7 5 6 8 9 10 11
  1 1 0 3 1 7 2 4 5 6 8 9 10 11
  2 1 0 2 1 11 3 4 5 7 6 10 8 9
  3 1 0 10 1 9 2 8 3 4 5 11 6 7
  -1 2 0 4 1 5 2 7 3 8 6 11 9 10
  0 2 0 10 1 2 3 4 5 7 6 9 8 11
  1 2 0 10 1 3 2 6 4 11 5 7 8 9
  2 2 0 5 1 11 2 4 3 9 6 7 8 10
  3 2 0 6 1 8 2 9 3 4 5 10 7 11
  0 3 0 9 1 3 2 11 4 5 6 8 7 10
  1 3 0 3 1 2 4 7 5 6 8 11 9 10
  2 3 0 1 2 10 3 9 4 11 5 8 6 7
  3 3 0 10 1 7 2 9 3 8 4 11 5 6
isTest: 'false'
isValidator: 'true'