title:
  1: Simple reuse
  2: Simple reuse
testIn: |-
  -3 -3 0 11 1 2 3 5 4 10 6 9 7 8
  -2 -3 0 4 1 11 2 7 3 5 6 8 9 10
  -1 -3 0 6 1 2 3 11 4 10 5 9 7 8
  0 -3 0 8 1 9 2 10 3 6 4 11 5 7
  -3 -2 0 8 1 9 2 4 3 6 5 10 7 11
  -2 -2 0 3 1 11 2 9 4 10 5 6 7 8
  -1 -2 0 1 2 8 3 9 4 11 5 7 6 10
  0 -2 0 5 1 7 2 10 3 6 4 9 8 11
  1 -2 0 6 1 2 3 8 4 9 5 11 7 10
  -3 -1 0 10 1 6 2 7 3 4 5 11 8 9
  -2 -1 0 1 2 3 4 9 5 11 6 7 8 10
  -1 -1 0 1 2 6 3 8 4 7 5 11 9 10
  0 -1 0 11 1 6 2 10 3 9 4 5 7 8
  1 -1 0 7 1 4 2 5 3 6 8 11 9 10
  2 -1 0 6 1 4 2 10 3 5 7 9 8 11
  -3 0 0 1 2 6 3 7 4 5 8 9 10 11
  -2 0 0 9 1 5 2 10 3 4 6 7 8 11
  -1 0 0 1 2 3 4 5 6 9 7 10 8 11
  1 0 0 9 1 2 3 8 4 6 5 7 10 11
  2 0 0 6 1 4 2 5 3 9 7 8 10 11
  3 0 0 9 1 2 3 8 4 6 5 7 10 11
  -2 1 0 7 1 8 2 3 4 5 6 9 10 11
  -1 1 0 9 1 2 3 8 4 5 6 11 7 10
  0 1 0 10 1 6 2 11 3 5 4 8 7 9
  1 1 0 6 1 5 2 4 3 9 7 10 8 11
  2 1 0 1 2 5 3 4 6 11 7 9 8 10
  3 1 0 11 1 3 2 5 4 6 7 8 9 10
  -1 2 0 7 1 9 2 11 3 4 5 8 6 10
  0 2 0 2 1 5 3 4 6 10 7 11 8 9
  1 2 0 3 1 11 2 5 4 6 7 9 8 10
  2 2 0 11 1 7 2 3 4 9 5 10 6 8
  3 2 0 8 1 9 2 3 4 10 5 6 7 11
  0 3 0 4 1 9 2 7 3 10 5 11 6 8
  1 3 0 1 2 9 3 4 5 6 7 8 10 11
  2 3 0 1 2 7 3 6 4 5 8 9 10 11
  3 3 0 4 1 3 2 11 5 7 6 9 8 10
isTest: 'false'
isValidator: 'true'